
services:
  pg_service:
    image: postgres:alpine
    container_name: ish_bor_pg
    restart: always
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    image: ish_bor_bot:latest
    container_name: ish_bor_bot_con
    restart: always
    command: python3 main.py
    depends_on:
      - pg_service

#  web:
#    build: .
#    image: kwork_web:latest
#    container_name: kwork_web_con
#    restart: always
#    command: uvicorn web.app:app -- host: 0.0.0.0 --port 8000
#    depends_on:
#      - pg_service
#    ports:
#      - "8000:8000"

volumes:
  pgdata:



#
#version: "2.35.1"
#
#services:
#  pg_service:
#    image : postgres:alpine
#    container_name: pg
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: 1
#    ports:
#      - "5434:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#  bot:
#    build: .
#    image: kwork_bot:latest
#    container_name: kwork_web_con
#    restart: always
#    command: python3 main.py
#    depends_on:
#      - pg_service
#
#volumes:
#  pgdata:
#
#
#

